lint-go:
  stage: test
  image: golangci/golangci-lint:v1.49
  script:
    - golangci-lint run -v

test-go:
  stage: test
  image: golang:1.18-alpine
  artifacts:
    reports:
      junit: junit*.xml
  before_script:
    - apk --no-cache add build-base
    - go get -v github.com/onsi/ginkgo/v2
    - go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
    - go get -v github.com/onsi/gomega
    - go get -v -t ./...
    - export PATH=$PATH:$HOME/go/bin
  script:
    - ginkgo -r --randomize-all --randomize-suites --fail-on-pending --cover --trace --race --progress -p --junit-report=junit.xml

